local h = require("tests.helpers")

require("tests.custom-asserts").register()

describe("non-ascii-specific-sequences-jump", function()
  describe("repeating-char", function()
    before_each(h.get_preset("ццццц", { 1, 2 }))

    it("forward", function()
      h.jump("forward", "none", "ц")
      assert.cursor_at(1, 3)
      h.jump("forward", "none", "ц")
      assert.cursor_at(1, 4)
    end)

    it("pre-forward", function()
      h.set_cursor(1, 1)
      h.jump("forward", "pre", "ц")
      assert.cursor_at(1, 2)
      h.jump("forward", "pre", "ц")
      assert.cursor_at(1, 3)
    end)

    it("backward", function()
      h.jump("backward", "none", "ц")
      assert.cursor_at(1, 1)
      h.jump("backward", "none", "ц")
      assert.cursor_at(1, 0)
    end)

    it("pre-backward", function()
      h.set_cursor(1, 3)
      h.jump("backward", "pre", "ц")
      assert.cursor_at(1, 2)
      h.jump("backward", "pre", "ц")
      assert.cursor_at(1, 1)
    end)
  end)

  describe("alternating-repeating-char", function()
    before_each(h.get_preset("ц ц ц ц ц", { 1, 4 }))

    it("forward", function()
      h.jump("forward", "none", "ц")
      assert.cursor_at(1, 6)
      h.jump("forward", "none", "ц")
      assert.cursor_at(1, 8)
    end)

    it("pre-forward", function()
      h.jump("forward", "pre", "ц")
      assert.cursor_at(1, 5)
      h.jump("forward", "pre", "ц")
      assert.cursor_at(1, 7)
    end)

    it("backward", function()
      h.jump("backward", "none", "ц")
      assert.cursor_at(1, 2)
      h.jump("backward", "none", "ц")
      assert.cursor_at(1, 0)
    end)

    it("pre-backward", function()
      h.jump("backward", "pre", "ц")
      assert.cursor_at(1, 3)
      h.jump("backward", "pre", "ц")
      assert.cursor_at(1, 1)
    end)
  end)
end)
